# Trigger this workflow on release
on:
  release:
    types: [published]

# Make sure the GITHUB_TOKEN has permission to upload to our releases
permissions:
  contents: write

jobs:
  build:
    name: "Build Linux standalone version"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: "Build YOGA Linux Standelone Version"
        run: |
          linux-bin/build.sh

      - name: Archive Linux Build
        uses: actions/upload-artifact@v4
        with:
          name: yoga-${{ github.event.release.tag_name }}_linux_standalone_x86-64
          path: yoga-bin.dist
      - name: "Upload to Github Release"
        run: |
          gh release upload ${{ github.event.release.tag_name }} yoga-${{ github.event.release.tag_name }}_linux_standalone_x86-64.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
